import Head from 'next/head';
import Image from 'next/image';
import styled from 'styled-components';
// eslint-disable-next-line import/no-extraneous-dependencies
import { makeId } from '@zeiq/core'; // run: npm link @zeiq/core
// eslint-disable-next-line import/no-extraneous-dependencies
import { Button } from '@zeiq/web'; // run: npm link @zeiq/web
import styles from '../styles/Home.module.css';

const Heading = styled.h1`
  color: ${(props) => props.theme.primaryColor};
`;

export default function Home() {
  const id = makeId(20);
  console.log('id', id);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Heading>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <p>some info here</p>
        </div>

        <Button />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
